### ISSUE TITLE
Japanese lyrics displaying incorrectly.

### ISSUE THREAD

**Issue by timf1256** [tripod31/get_lyric#1]
![capture](https://user-images.githubusercontent.com/21978258/29442715-58167b30-83a1-11e7-856f-8b026286c89f.PNG)

Hello,
I don't know if this is a problem on my end.  It happens in a regular command prompt as well, not just in cmder.

**Comment by tripod31** [comment]
Hello.
I tried with windows10pro64bit japanese edition.In command prompt,change encoding to unicode with following command.
`chcp 65001`
and I could get the lyric in japanese.
I noticed that foo_lyricsource.dll can't get japanese lyric from get_lyric.exe.Maybe other non ascii lyrics are the same.I think that it is the issue of lyrics_source_sdk and I can't fix it.

**Comment by timf1256** [comment]
Hello,
Thank you.  I reinstalled Windows 7 recently.  I forgot to set locale to Japanese.  It is working now.
You are correct.  The lyrics don't import to foobar.
